### ISSUE TITLE
[BUG] During Timeout, Jam Start button should not be hidden by "---", and starting the Jam should stop the Timeout clock

### ISSUE THREAD

**Issue by megapickle18** [rollerderby/scoreboard#802] opened 2024-11-19 22:03 UTC
**Describe the bug**
The design decision to hide the Jam Start button during a Timeout prevents the operator from using the standard operating procedure for how Timeouts are supposed to end. Per the latest WFTDA official guidance, we should not display a Lineup Clock between the end of the Timeout and the start of the subsequent Jam start. We have been told to simply let the Timeout clock continue running until the moment that the next Jam actually starts. If we press the "---" button (where the Jam Start button used to be), the next jam does indeed start, but the Timeout clock is still running in the background, which then causes a problem when the next Timeout needs to be called.

**To Reproduce**
1. Start a Timeout.
2. Try to simply start the next Jam.

**Expected behavior**
This process had been handled correctly by v2023 and all previous versions. When the Jam Start button was pressed, the Timeout clock was simultaneously stopped automatically. This behavior is not only expected by the operator, but by the global parent organization.

**Version:**
v2025.0 and v2025.1

**Comment by megapickle18** [comment] 2024-11-19 23:11
I see previous threads have gone nowhere, and bugs closed, because there is apparently a misconception that the Timeout clock must end before the new Jam can start. Please honor the directives given by WFTDA in their Officiating Procedures document, emphasis mine:

> 4.8 When returning from a Timeout, the scoreboard should allow the timeout clock to continue to run and **_go right from the timeout clock into the start of the next jam_**. The Jam Timer will start the next jam at either 30 seconds after the end of the timeout, or when both teams are ready, whichever is first. DO NOT start the lineup clock and stop the timeout clock.

**Comment by frank-weinberg** [comment] 2024-11-19 23:30
Going straight from a timeout to a jam was operator error in all CRG versions since 4.0.0, released in 2019 (see https://github.com/rollerderby/scoreboard/wiki/Changes-in-Version-4 where the required SBO procedure change is mentioned in bold face). Doing so causes the recorded data to be wrong. The fact that the button still read "Start Jam" was a bug that has been fixed in the new version. The fact that in earlier versions the error didn't have any further impact was just lucky(?) for all the people that made this error. An unrelated change caused it to go from barely noticeable to possibly disturbing game flow in the beta versions. I was able to reduce it back to a level of slightly annoying but that's as good as it'll get.

As to that WFTDA procedure:

The procedure was only added earlier this year at a time when following it was an operator error in any even remotely recent version of CRG. Thus it is WFTDA who are diverting from established procedure, not CRG.

The procedure is arguably also incompatible with the rules. The fact that a jam is about to start is critical game information in my opinion - missing it can cause your captain to be penalized or your team to skate short. Thus it has to be highly visible as per 1.4 and having the scoreboard look as if the timeout was still ongoing is the opposite of that.

Why WFTDA is putting out a procedure that is incompatible with their own rules and with the software used in 99% of WFTDA rules games is an open question. My inquiries ran dead since apparently nobody at WFTDA is even willing to own this procedure. The procedure was communicated by OffEd but when discussions started they claimed that the board requested the changes and they were just the messenger. When I asked the board about the changes they were not even aware that the officiating procedures had been changed, let alone the contents of the change. The board went on to promise setting up a meeting with stakeholders of CRG and the officiating procedures in order to make sure they are better aligned in the future. The timeline given was "once Regionals are over". So far I have not heard anything further on this.

Given that 
a) WFTDA is completely refusing to justify this procedure on either the forums or direct communication and the only argument for it that community members have come up with is unconvincing¹ and
b) making CRG compliant with the procedure would break existing features (among others the ability to enter ORs for the statsbook)
I have no intention of changing CRG just to make it compliant.



¹ The claim is that it could confuse people when a Jam starts with the lineup clock not at 30. Evidence from all over Europe and Oceania shows that this is not the case. And the potential problems from hiding the fact that a jam is about to start are worse than a few confused audience members anyway.

**Closed as not planned by frank-weinberg** 2024-11-19 23:30 UTC
Labels: Feature Request

**Comment by Capt-Brunch** [comment] 2024-11-20 01:02
@frank-weinberg as someone who previously raised this issue before it changed from "game impactful" to "mildly annoying", I don't think I ever saw an update on the idea that the start jam button, if mistakenly clicked, could just also run whatever method ends a timeout.

This _would not_ be a UI change,a new button or anything of the sort. It would simply be automatically correcting an operator error, in the same way that adding points before adding an initial trip is (mostly) silently corrected.

If you really want, you could make it mark a red dot of shame to call the operator out for this behavior I guess, but I categorically fail to understand how it's even remotely possible for "if a timeout is running when the operator starts a jam, automatically end that timeout" to break any other functionality. Simply treat that button click as very rapidly doing two actions. There's precedent for this type of "silent fix" already.

**Comment by frank-weinberg** [comment] 2024-11-20 08:17
CRG 2025 supports a ruleset option to run a "Timeout Jam" where the period clock remains stopped. I don't expect this option to see particularly widespread use but it is there for those that want to experiment with it and automatically ending the timeout on jam start would break it.

Also, unless you forget to press "End Timeout" on the last timeout of a period and then don't notice and fix it, it will have no impact visible outside of the operator screen (and in the data, where a fix is impossible anyway). So it is already at "red dot of shame" level.

**Comment by bullseye555** [comment] 2024-12-06 10:20
@frank-weinberg 
There has been some lively discussion on Facebook about this and one question has kept coming up: 
Which ruleset has the _Timeout Jam_ option? 

There was also a suggestion raised, as there is already a Ruleset option for a _Timeout Jam_, that when this is disabled the "Start Jam & Stop Timeout simultaneously" function is enabled - and only when it is _enabled_ that the current behaviour of 2025.3 kicks in
![image](https://github.com/user-attachments/assets/7476a57b-ed97-4382-b99a-3e230882d8d3)

**Comment by frank-weinberg** [comment] 2024-12-06 17:35
"Has kept coming up" - it was brought up once. But alas, that's about the level of accuracy as that discussion has in general.

- @AdamSmasherDerby  seems to have forgotten that it was me who worked with him to get a compromise for the Initial Trip Issue implemented against strong opposition from the other developer, who afterwards quit the project in protest. So claiming that I am unwilling to listen to users feels unfair even when going by how that issue was handled alone (and even more so regarding my other work on this project).

- So it is an unacceptable abuse of power if CRG requires NA officials to mark the end of a timeout in order to generate complete stats. But if WFTDA forbids Europe/Oceania officials from doing so without giving ANY justification at all that's not to be questioned? Ridiculous.

And to the question from the OP: If you let the timeout run and stop it after the end of the next jam, you are in compliance with the holy procedure and stats won't be more broken than in earlier versions. (Arguably even less broken as CRG will now record the timeout duration as "Unknown" in that case.) And for the love of your JTs: Don't reset the clock during the 5 seconds. That's really nasty for a JT who's whistling by the official clock (i.e. the scoreboard). In addition it is compliant with neither WFTDA nor CRG procedure, so you get the worst of all worlds.
Also: The Officiating Procedures don't just apply to sanctioned play, they apply to regulation games as well. (See Sanctioning Policy.) If you want to be pedantic about procedures, you should know them completely.

And if you want to be compliant with the holy procedure without breaking CRG you can't go back to 2023.7, you have to go back to [3.9.5](https://github.com/rollerderby/scoreboard/releases/tag/v3.9.5). Unless you interpret the procedure to only be about what is visible on the scoreboard and not about what buttons to press. Then the "Clock After Timeout -> Timeout" setting would be a way out. Funny how nobody is requesting that. Maybe the issue isn't actually which clock is displayed but that people are unwilling to add a single button press to their routine in exchange for getting to use all the "cool new features".

As to resolving the situation with the incompatible procedures: I've had a talk with Bones last night and there is some rekindled hope that the relevant people at WFTDA will actually get in contact to talk about things sometime soon.

**Comment by AdamSmasherDerby** [comment] 2024-12-06 18:01
My recollection is that "working with me" meant insisting that I spend a month figuring out how to code it myself when either of you could have done it in ten minutes, then demanding I write code for a "notation" function that I also had to work out how to implement, before you'd agree to the initial trip pull request.

All to stop the software from defaulting to a literally impossible gamestate.

"So it is an unacceptable abuse of power if CRG requires NA officials to mark the end of a timeout in order to generate complete stats. But if WFTDA forbids Europe/Oceania officials from doing so without giving ANY justification at all that's not to be questioned? Ridiculous."

The software is not a governing body.  It is not ridiculous when the governing body sets policy, and it IS ridiculous if someone OTHER than the governing body sets policy.

I've said it before, and I'll say it again - the software should function the way the users expect it to.  Demanding the users function the way the SOFTWARE expects them to is backwards.

**Comment by AdamSmasherDerby** [comment] 2024-12-06 18:04
As far as the policy being about what's on the scoreboard vs. what buttons to press.

Of COURSE the policy is only about what's visible on the scoreboard.  No one else in the venue knows or cares what buttons are bing pressed, and no WFTDA policy requires collection of timeout data.  The ONLY thing that matters by the policy is what is displayed on screen.

**Comment by reflexdd** [comment] 2024-12-06 18:24
And that’s the point. There are different views on how the software should work. Most European officials would probably like to end a timeout first  instead of going directly to start a jam. So users would expect this behavior. 

And for sure the procedures need to be discussed between WFTDA and devs.


I would agree to at least stop a timeout by default if a jam is going to be started. This would at least avoid people being presented the „End Timeout“ + „New Timeout“ Choice. I can see that people would be confused about the two options.

> Am 06.12.2024 um 19:02 schrieb Adam Smasher ***@***.***>:
> 
> I've said it before, and I'll say it again - the software should function the way the users expect it to. Demanding the users function the way the SOFTWARE expects them to is backwards.

**Comment by reflexdd** [comment] 2024-12-06 18:30
And what we don’t see on the screen in that case would be that a timeout has ended. And this should be something what audience, skaters and officials should be aware of. 
This whole procedure thing needs to be discussed carefully between WFTDA and the community. And thats hopefully happening soon :)

**Comment by frank-weinberg** [comment] 2024-12-06 23:48
> "working with me"

I tried to resolve that politically difficult situation in a way that was compatible with the agreement we had in place as to how we handle developer disagreements and I explained that at the time. Turned out to be moot after the fact anyways but hindsight is 20/20.
And I am not claiming that I handled this in the best possible way or that you should be happy with what happened. But saying that I was "unwilling to listen" is not a fair representation of what went down.

> literally impossible gamestate

Very very unlikely but not impossible.

> It is not ridiculous when the governing body sets policy,

It is when it is done by people who have no mandate to set policy. Ump posted in the name of OffEd and during the discussion claimed that OffEd was actually asked by the board to do it. But the board didn't even know about the change. The committee that should be in charge of officiating procedures (Officiating Theory) does not currently exist and Bones (who generally has the best overview of things happening at WFTDA) believes this was done by a small group of individuals with no mandate. If that's the standard of how changes to this policy are put in place by the governing body then how about Rankings posting a document next week that replaces this procedure with one that states: "The operating instructions of any software being used should be followed." And then maybe the week after Cert or whoever posts another version. Sounds like a great way to organize a sport. Not.

> the software should function the way the users expect it to.

If you really believe this statement without restriction: The statsbook tool is able to tell me that some findings are from substitutes. As a user I expect it to filter those out in the first place. I don't care if this breaks other features that you consider more important. My convenience is the top consideration you should have in mind when deciding what you work on in your spare time. On that note, another bug is that the tool does not automatically find and open the statsbook I most recently downloaded to my computer.
If not: Where are the limits to what users can demand? Clearly there are (combinations of) things that are impossible like not pressing any button when a timeout ends but still reporting the correct duration for that timeout. And in conflicting cases who gets to determine which is more important, i.e.  who are "the users" that get to make demands? The people who shout loudest in a random Facebook group? Or those on the WFTDA forums? The CRG slack? This github repo? The sport hall I happen to officiate my next game in? Or maybe those that pay for development - in this case through donating their time and expertise?

> Of COURSE the policy is only about what's visible on the scoreboard.

This doesn't seem to be obvious to many people in the discussion who treat it as forbidding a button press even if that button press does not change which clock is displayed. But if that's the only issue, I can revert to the state in the beta where the "Clock After Timeout" setting was still available. (This would have the side effect that an unstopped timeout would hide lineup clocks consistently as it requires to give the timeout clock higher priority. This would in turn increase the pressure on the SBO to stop the timeout quickly. But if people consider this to be an acceptable trade off, I'm fine with that. It shouldn't happen that often anyways once people got used to pressing the button.)

**Comment by JeneralPain** [comment] 2024-12-08 08:59
> But if WFTDA forbids Europe/Oceania officials from doing so without giving ANY justification at all that's not to be questioned? Ridiculous.

The stats generation would have nothing to do with location in my mind. It would simply be the game state for the way javascript adjusts from state to state. I used to do it because I knew some jam timers preferred to see "the 30 seconds", and it helped others see we were getting started.

> Sounds like a great way to organize a sport. Not.

We need to work collaboratively not attack each other, it really doesn't work if all we're going to do is pointlessly argue. 

> does not currently exist and Bones (who generally has the best overview of things happening at WFTDA) believes this was done by a small group of individuals with no mandate. If that's the standard of how changes to this policy are put in place
Given the lack of source for this info, I'm finding it more predjuicial than useful in the context of this conversation.

Honestly the last few comments on this thread have been horribly counter productive and not at all in the spirit of the sport we love, OR SPORT IN GENERAL. Please, I have no problem with people putting their point of view across, but at the detriment to others... not so much.

**Comment by The--Captain** [comment] 2024-12-08 10:16
Jon Fox here...

I don't want to get into any of ^that, but I would like to make a humble suggestion.  Some of what I suggest may not be possible; Frank can probably point that out if I get too fanciful, but here it goes:

First, before I make a total ass out of myself, am I correct in thinking that current WFTDA rules (or at least for some high-level tournaments) dictate tracking of correct timeout length, that excludes the non-specific amount of time allowed between the end of a timeout and the beginning of the next jam?  Just want to be sure I understand the crux of the issue here.

If that interpretation is accurate, then I propose a ruleset option along the lines of "Starting jam stops timeout".  This would obviously be exclusionary to the option that allows timeouts to run during jams - I saw some mention of that rarely used config, but is there really any reason that both cannot coexist in the software, as long as one option excludes the other?

I admit to being clueless about how the statsbook generation works - might it be possible to add an indicator that the timeout value was "tainted" if "Starting jam stops timeout" was enabled, and the timeout clock was indeed not stopped prior to the nexxt jam?  It could even include a+/- percentage of error, assuming a max 30s lineup and a min of say 10s (since the rolling whistle is hardly ever immediately proceeded my "5 SECONDS!" from the jam timer).  If none of that is possible can we just put in a null or nonsense value (e.g. -1) that indicates that it could not be computed or accurately recorded?  I personally think that would be silly given that we could just put in the total value of timeout plus the nonspecific amount of proceeding "lineup" time (if we can't delineate between end of timeout and allotted time to return to track, the total time is all we have to work with), and the statsbook itself could just have a general indicator that timeout values were inflated.

I agree that as things stand a "Stop timeout" button is totally logical and necessary, but when a WFTDA ruleset is selected it should not be possible for a timeout clock to run simultaneously alongside  a jam clock.   Is adding ruleset option(s) not possible?  If I missed exactly why this is not possible, please accept my apologies, but could you please link to the explanation (and forgive me for being forgetful/clueless)?

Yes I know this is a poor use of github issue submission functionality, however it seems beyond most of the noise on soc med but still where issues can endure reasonable debate
 
Thanks
Jon

**Comment by AdamSmasherDerby** [comment] 2024-12-08 15:51
@The--Captain here's what is officially required by WFTDA:

```
From the rules: (1.4)
This must be displayed.
* The period clock
* The jam clock
* The official score

Team Timeouts are 60 seconds long
Ater a timeout, teams have at most 30 seconds to resume play.
```

There is no requirement to display a lineup time at ANY point, although obviously that's preferred. Obviosly someone must be TIMING the linup period, as lineup clocks are mentioned in the official procedures, but that can legally be a stopwatch in the hand of the Jam Timer, even for sanctioned play.

```
From the Statsbook Manual:
"The "Official Reviews" sheet is optional, but strongly encouraged."
"Length of Review: The amount of timeout time shown on the scoreboard when the review
ended."
```

This is literally the only place that tracking timing of anything related to timeouts or lineups is mentioned.  Tracking the length of the OR is optional.  Tracking the length of lineups after the fact is not required in any way, shape, or form.

```
From the Officiating Procedures:
"Do NOT start the lineup clock and stop the timeout clock." (4.8)
```

Unless I've missed something (and leaving aside the weirdness about a timeout in the last thirty seconds), this is the ONLY official verbiage that relates to this topic.
