### ISSUE TITLE
[BUG] 2025.2 Timeouts not ending on jam start

### ISSUE THREAD

**Issue by kel-to-pay** [rollerderby/scoreboard#806] opened 2024-12-01 13:05 UTC
**Describe the bug**
As per WFTDA Officiating Procedures 4.8, I left the timeout clock running before going into the next jam
Throughout all 3 games yesterday, the timeout never ended on jam start. As can be seen in screenshot 3, despite originally assigning the timeout between jams 1 and 2 as an OTO, between jams 2 and 3, I pressed TTO, and the timeout from jams 1 and 2 changed from OTO to TTO.

This lead to one instance of the JT having to correct the period clock with their backup by approx 15 seconds, as I had pressed OTO, expecting a new timeout instance to occur. Whilst I was assisting a newer SK in the OTO, I noticed that the lineup clock and period clock had not stopped and immediately ended the timeout and started a new one. 

I appreciate that there has been consternation over 4.8, but it is the standard we are held to as scoreboard operators, and I would expect CRG to support that by default

**To Reproduce**
1. Load any game
2. Start a jam
3. End a jam, then go into a timeout
4. Leave the timeout clock running as skaters lineup
5. Press start jam, timeout clock continues to run in the backgroup
6. End the jam
7. Press OTO, TTO, or OR, and the timeout running in the background changes to whatever you have selected, and the period/lineup clocks continue to run until "end timeout" and "new timeout" are pressed

**Expected behavior**
As per older versions of CRG, when a new jam is started, the running timeout clock should stop, with the period and jam clocks starting.

**Screenshots**
![image](https://github.com/user-attachments/assets/198ad465-74f5-499c-a5ea-54919a7f7f14)
1 - Period/Jam/Timeout clocks running
![image](https://github.com/user-attachments/assets/9a270dd1-6e33-44d9-a4d4-be6120a4b4db)
2 - Period/Lineup/Timeout clocks running
![image](https://github.com/user-attachments/assets/b9ca6c2f-4b84-44bc-a263-7318be500843)
3 - Note timeout still registering as between jams 1 and 2, even if I press TTO or OR, it is still the same timeout that has not ended
![image](https://github.com/user-attachments/assets/84bfcea5-c089-4ddb-8390-82340fa44238)
4 - WFTDA Officiating Procedures section 4.8

**Version:**
2025.2
Link to zip of the game folder at end of the game state
https://drive.google.com/file/d/1IxZ912mv96iMByhTsIozgVY778U-g6pi/view?usp=sharing

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: Windows 10 22H2
 - Browser: Chrome
 - Version: 131.0.6778.86 (Official Build) (64-bit)

**Comment by frank-weinberg** [comment] 2024-12-01 13:38
Having to press "End Timeout" at the rolling whistle is a mandatory step in CRG since 4.0.0 in 2019. (See https://github.com/rollerderby/scoreboard/wiki/Changes-in-Version-4 fore reference - the change in procedure is highlighted in bold.)
WFTDA releasing a procedure that contradicts the operating instructions of the software used in >90% of WFTDA games without giving any rationale for the change, even when asked, is a WFTDA problem not a CRG problem.

(Duplicate of #802)

P.S.: Rereading that procedure it also states that when both teams are ready after a timeout but the officials are not, the jam should still start immediately. I have yet to see a single person to argue for applying that part.

**Closed as not planned by frank-weinberg** 2024-12-01 13:38 UTC
Labels: bug
