### ISSUE TITLE
[BUG] Skater Flags not Retained for Saved Teams

### ISSUE THREAD

**Issue by mistress-of-evil** [rollerderby/scoreboard#689] opened 2024-04-04 03:21 UTC
**Describe the bug**
When pulling up an existing team, all listed members show as Skaters. Changing a flag to "Bench Alt Captain", "Bench Staff", or "Captain" and syncing those changes should keep those flags for the next time that team is used.

**To Reproduce**
1. Go to Teams
2. Click on Custom Teams list
3. Scroll down to select an existing team
4. Update a skater Flag to a non-skating role
5. Sync changes
6. Select "Custom Team" or another saved team
7. Switch back to the edited team

**Expected behavior**
I expect the flags for non-skater roles to be retained from the last sync of the team details.

**Version:**
The version of the scoreboard you were running: 2023.5 / 2023-11-26 - Latest on Nov 26, 2023

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: Mac OS 12.7.2 (21G1974)
 - Browser: Chrome
 - Version: 123.0.6312.87 (Official Build) (x86_64)

**Additional context**
I was prepping teams for an upcoming bout - and I realize the flags can change bout to bout, so this might not actually be a bug. It was different than what I expected, however, so I'm flagging it for review.

**Comment by bullseye555** [comment] 2024-04-05 08:44
@frank-weinberg confirming I've been able to replicate this, and validated that sync'ing _does_ occur by also altering the roster in other ways (changing numbers, names, & pronouns, and deleting & adding people)

I'd expect the _Flags_ to sync through to the stored team too

**Comment by frank-weinberg** [comment] 2024-04-07 12:22
From https://github.com/rollerderby/scoreboard/wiki/Team-Editor:
> - Alternate names, colors, and skater flags are only copied on initial load but not synced.

-> closing this as not a bug

**Comment by mistress-of-evil** [comment] 2024-04-07 12:40
Thank you for confirming :)

Thanks,
-MoE

**Closed as not planned** 2024-04-07 12:49 UTC
Labels: bug
