### ISSUE TITLE
Logo and colors not loaded

### ISSUE THREAD

**Issue by Jill-DL** [rollerderby/scoreboard#508] opened 2022-05-13 15:54 UTC
(Windows, v5.0.2)
When loading a prepared game or starting a game with prepared teams, despite being visible on the SBO interface, the team colors aren't shown on the main scoreboard or the overlay. Additionally, the uniform colors and logos aren't loaded at all.
PS : could it be possible to have more than one color set per team, attached to the uniform color?

**Comment by frank-weinberg** [comment] 2022-05-13 17:25
- I can reproduce the issue with colors not being applied to the main display and overlay until they are changed again.
- I can also reproduce the issue with the logo being unset on the prepared team instead of being copied to the per game team.
- I can **not** reproduce the issue with uniform colors - for me all uniform colors are consistently listed in the dropdown on the per game team.

But while I can reproduce the first two issues, I don't (yet) understand what causes either of them after some initial research. So they appear to be nontrivial and it may take a bit to get to the bottom of them and produce a fix.

Regarding the PS: One set of colors per uniform color, while possible in principle, would be a rather large effort. Even more so if we want to keep the option of only having a single set of colors. I'm not sure it's useful enough to be worth that effort. (But my estimation of how useful it is may be affected by the fact that I personally don't use colors.)

**Comment by Jill-DL** [comment] 2022-05-13 17:29
Sorry, I meant that the uniform colors picked in the list when preparing the game do not appear preselected when loading said game. They do indeed appear in the dropdown.
Thanks for taking this into account

**Comment by frank-weinberg** [comment] 2022-05-13 17:42
That also works for me - I select e.g. Black when preparing and after loading Black is selected. - Switched back and forth between two games multiple times and it worked everytime. If you have a game that doesn't work, I'd be interested in the data file so I can see what is different about it.

**Comment by Jill-DL** [comment] 2022-05-13 18:12
I can't seem to reproduce it now. I must have made a mistake earlier. Sorry!

**Comment by frank-weinberg** [comment] 2022-05-15 15:20
I found the sources of the bugs. Fixes will be in v5.0.3.

**Closed as completed** 2022-05-15 15:21 UTC
Labels: bug
