### ISSUE TITLE
[FAULT] Scoreboard coming out of half time locked at 1 second and no commands

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#698] opened 2024-05-18 00:58 UTC
**Describe the bug**
The scoreboard was left in "half time" / intermission for the standard 15 minutes. At 1 second left, the clock stopped. The scoreboard was unresponsive to all commands (start/stop/timeout/etc etc).

**To Reproduce**
Steps to reproduce the behaviour:
No steps - it just hung.

**Expected behavior**
Drop into "P2 Coming Up"

**Screenshots**
none taken

**Version:**
2023.6

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: Windows 10
 - Browser Chrome
 - Version Latest

**Additional context**
Investigating the crg.log file showed no errors.
Simply stopping the JRE window and restarting the exe resolved the fault. Restoring it to the position it should have beben.

**Comment by JeneralPain** [comment] 2024-05-19 11:53
I enabled debug level logging via the appropriate -Dorg command and there was nothing found in this scenario. Even in the =WARN level, nothing was output to the crg log either.

**Comment by frank-weinberg** [comment] 2024-05-19 12:34
Please clarify: Was this a one-off thing or did it happen repeatedly. (And if repeatedly, with what frequency?)

**Comment by JeneralPain** [comment] 2024-05-19 12:39
Hi Frank,

It happened with every single game, and only cleared when you restarted the
whole instance of the SB. 5 games, happened 5 times.

Jen

**Comment by frank-weinberg** [comment] 2024-05-19 12:56
Doesn't happen for me, so either dependent on the device or the data. Can you attach an export of the scoreboard data?

And knowing if it happens with a clean install on the same computer could also be useful.

**Comment by JeneralPain** [comment] 2024-05-19 19:25
My first concern was that older folders of previous builds were on the same desktop.I'll get bullseye to do an entire folder upload for you to have a look at, along with the console output when debug was running l, that said it only had approx 50 lines.Sent from my iPhoneOn 19 May 2024, at 22:56, frank-weinberg ***@***.***> wrote:﻿
Doesn't happen for me, so either dependent on the device or the data. Can you attach an export of the scoreboard data?
And knowing if it happens with a clean install on the same computer could also be useful.

**Comment by bullseye555** [comment] 2024-06-03 08:18
https://drive.google.com/file/d/1CEe-teTxLo_-_X8seiydgWeHVxWvALYN/view?usp=sharing

File was too big to upload direct to git, so here's a google drive link

**Comment by frank-weinberg** [comment] 2024-06-23 20:04
Weird one. There is nothing in the data that points to a culprit - intermission clock is at exactly 1000ms and running. But it's the same in the 60s ago autosave. So the autosave thread was running but the clock thread was deadlocked. As were presumably all other threads that tried to set game state.
Now the question is what was reproducibly triggering this at exactly this time. There is nothing in CRG that runs at 1s remaining on the intermission clock. There is also no custom screen in the zip that could have triggered anything. I'm at a loss.

**Comment by frank-weinberg** [comment] 2024-09-15 15:34
Closing this as there is no info coming and chances are it has been fixed by the changes made since the affected version.

**Closed as not planned by frank-weinberg** 2024-09-15 15:34 UTC
Labels: bug, input needed
