### ISSUE TITLE
[BUG REPORT] - Multiple bugs (IGRF Export, Ruleset for AdHoc games)

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#525] opened 2022-08-04 01:03 UTC
Bug 1 (This is one I found): When downloading StatsBook after setting the _Teams_ for each of PBT, PLT etc, the Official name isn't populated into the _Penalty Box_ sheet
![image](https://user-images.githubusercontent.com/28804763/182736431-24a2b0a4-9813-450f-84bb-20ac8b5918a3.png)
Expecting _Intensive Claire Unit_ and _Bash A Lot_ to be populated in the statsbook
![image](https://user-images.githubusercontent.com/28804763/182736460-3f50c950-b645-47bc-8024-236cb7811d87.png)

Bug 2 (Reported via the FB group and I've been able to replicate):  Starting a game with a ruleset other than WFTDA doesn't honour the changes in the selected ruleset
This applies to both pre-built rulesets (eg: RDCL, RDCL half game, Sevens)
Select Teams and Ruleset, no start time. Select Start Game
![image](https://user-images.githubusercontent.com/28804763/182737883-608790aa-599b-4136-b74a-5f77ffe4767b.png)
Go to current game
![image](https://user-images.githubusercontent.com/28804763/182737899-83cef352-19f3-4caa-a64b-81f22609eddf.png)
Sevens ruleset should have a 21min half
![image](https://user-images.githubusercontent.com/28804763/182737921-9b12cda4-71fd-439e-b8be-fa8ae4e2f99c.png)
**Rules** page shows WFTDA as the ruleset applied (when using a custom ruleset, this shows **Custom** instead of the name of the actual ruleset selected, and doesn't inherit any of the selected ruleset changes)
![image](https://user-images.githubusercontent.com/28804763/182737948-36ade561-8379-4838-b6aa-1dd2c27d5e1c.png)
  -- Custom ruleset created was **JRDA**; none of the changes made (such as custom Penalty Definition File) were inherited into the **Custom** ruleset that was created
![image](https://user-images.githubusercontent.com/28804763/182738521-f869a203-9dd8-4710-bb41-a8e494d5cc5a.png)

Manually updating the ruleset correctly honours the ruleset
![image](https://user-images.githubusercontent.com/28804763/182738066-22ecad64-5fad-44d7-a485-8d8a914a1ceb.png)
![image](https://user-images.githubusercontent.com/28804763/182738079-837709fc-a3e2-411f-9c70-f1bbe587882a.png)

There doesn't appear to be any issues in starting a Prepared Game with a different ruleset - both an uploaded IGRF with the ruleset changed, and a game entered directly both had the changed ruleset honoured on game-start

**Comment by frank-weinberg** [comment] 2022-08-04 20:31
I'm not sure what you mean with 

> (when using a custom ruleset, this shows Custom instead of the name of the actual ruleset selected, and doesn't inherit any of the selected ruleset changes)

Aside from that I found the source of Bug 2 and a fix will be in the next release.

"Bug" 1 is not a bug but a feature request in my book - I never considered adding names to the Box Sheets as they are not typed into the statsbook. But I guess it may be useful for preparing paperwork if the team assignment is already known at that time. So this will also be in the next release.

Release ETA: Once I have gotten around to investigating and fixing the bugs reported via another channel. I hope that's some time next week but can't make any promises.

**Comment by bullseye555** [comment] 2022-08-05 05:48
Thanks Frank

`I'm not sure what you mean with

`(when using a custom ruleset, this shows Custom instead of the name of the actual ruleset selected, and doesn't inherit any of the selected ruleset changes)``
When a custom ruleset (eg, one that is created and not a ruleset included with CRG -- in my example, I've used **JRDA**) is selected as part of the _AdHoc_ game creation, when the game is started and you navigate to the _Rules_ tab, it shows the word **Custom** instead of **JRDA**, and doesn't show any of the changes to the original parent rulset made when creating the **JRDA** ruleset.

Re: Bug/Feature 1
Understood - every tournament I've ever done statsbook entry for the PBT paperwork has always been input

**Closed as completed** 2022-08-12 16:22 UTC
Labels: bug, Feature Request
