### ISSUE TITLE
Editing historical jams fails to update "current" official score.

### ISSUE THREAD

**Issue by admdikramr** [rollerderby/scoreboard#623] opened 2023-05-14 22:43 UTC
1. Run Jam 6, which has 4 + 1 = 5 points.
2. Run a few more jams, until there is a timeout.
3. Realize that Jam 6 was an accident, those points were scored in Jam 5, and the Scoreboard is incorrectly ahead by one jam.
4. Go into the history; add the 4 + 1 to Jam 5.

Issue: These points are not added to the initial score. They are incorrectly assumed, without telling the user or seeking input from the user, to be a "score offset" that is not valid. Correct behavior should ask the user whether the points are "real" or an offset.

5. Remove the points from Jam 6.

Issue: Same issue occurs. The result is that the visible points appear to be correct, because the two incorrect offset assumptions cancel out.

6. Delete Jam 6, fixing the current jam count.

Issue: The offset from 5 has been deleted, which means the offset from 4 has removed five points from the current visible score, resulting in a scoring error.

If my SK hadn't seen it RIGHT THEN during the timeout, the above process would have resulted in an actual scoring deficit.

Expected behavior: Editing prior jams' points during a RUNNING game (where there is time on the period clock) should ask the user whether an edit to a prior jam is an offset (which should not be counted towards the visible score), or a correction (which should).

Expected behavior: Deleting a jam which has a score offset in it should alert the user to the fact that the offset is disappearing, which will result in a change to the visible score.

**Comment by JeneralPain** [comment] 2023-05-14 23:11
My concern here is:
https://rules.wftda.com/03_scoring.html#errors-in-scoring-score-reporting

3.5 says if it happened in Jam 5, you had until the conclusion of Jam 6 fix
it (the real Jam 6).

So based on that, the score correctly did not update based on "run a few
more jams".

This is the expected behaviour in line with rule 3.5

**Comment by WishboneBreaker** [comment] 2023-05-14 23:33
> My concern here is: https://rules.wftda.com/03_scoring.html#errors-in-scoring-score-reporting 3.5 says if it happened in Jam 5, you had until the conclusion of Jam 6 fix it (the real Jam 6). So based on that, the score correctly did not update based on "run a few more jams". This is the expected behaviour in line with rule 3.5

The correct score was displayed, it sounds like, in accordance with the WFTDA rules. It's just the points were applied in an erroneous jam that never existed. What's the correct way during the game to fix this, then, so the correct jam number displays?

**Comment by JeneralPain** [comment] 2023-05-14 23:42
That makes more sense, I might have to try and recreate this scenario on a
test server and see if I can work out how to as many have described "reduce
the trauma".

**Comment by admdikramr** [comment] 2023-05-15 01:50
In this scenario, CRG is in direct violation of rule 3.5, where it says, "However, points awarded (or denied) correctly, given the information available at the time, may not be taken away (or awarded) later."

If I have correctly added points that were correctly shown in the official score (step 1, in my note), then when I do the fix, CRG's behavior removes them from the official score. That is a violation of the rule.

I understand the argument that me editing a prior jam's score past the deadline COULD be a violation of 3.5 (a correction that is "too late"), but CRG cannot tell if that is the case.

The issue I am raising is that the specific situation needs greater visibility -- editing a "too long ago" jam should force the user to specify whether this is an offset (don't update the actual score), or a correction to the paperwork (actually update the actual score).

However, this is still a bug even if you choose to ignore the part of Rule 3.5 that CRG is violating, and focus only on the "time limit" aspect: Deleting a jam with points, that have been corrected to be zero points as a score offset, actually removes the points from the current visible score even if the jam happened long ago. I.e., the "can't delete a jam with points" logic is applied only to the visible points, not the as-recorded points.

In last night's game, just to be very clear about things: CRG's internal paperwork incorrectly had a jam due to an error. Recovery from the error required eliminating a jam. CRG's internal paperwork incorrectly attributed points to that jam. The fix was to attribute the points to the jam in which they were actually accurately scored. The official score was correct the entire time, and CRG's handling of the correction of the paperwork caused the displayed score to be incorrect in a way that violates the rule.

**Comment by bullseye555** [comment] 2023-05-15 01:58
My initial thought in this scenario would be the ability to "move trip" -
eg, select Trip 2 (initial scoring pass) for Jam 6 specify that the pints
be moved to Trip 4 of Jam 5.
This the removes the points from the Jam in question, without altering the
score, and then Jam 6 can be deleted without impacting the score

**Comment by frank-weinberg** [comment] 2023-05-15 06:52
ad 3: How do you even do this? The common way to get a non-jam is to start a jam when there should have been a timeout and then quickly pressing timeout instead of using undo+replace. But that doesn't put points in the non-jam.

ad 4,5: This is not silent. When the jam has an OS offset there is an indicator on the jam score. And opening a "Do you really want to edit the points?" popup for an inline edit is an absolute no go as that would block hotkeys. It would also require duplicating the detection of when a change causes an OS offset in the frontend, which is cumbersome and error-prone. Finally, the instances where a change of an old scoring trip should not cause an OS offset are so rare that the ability to manually remove the OS offset afterwards should be sufficient.

ad 6: The correct behavior is that a jam that has no points but an OS offset should not be able to be deleted, just like a jam with points. If the OS offset should not be there it can be manually removed just like the points.

**Comment by WishboneBreaker** [comment] 2023-05-15 11:04
@admdikramr would it have been more obvious that there was offsets happening in the paperwork if the easily miss-able red dot was instead the trip colored red? As in "I'm red because my points aren't actually reflected in the score"?

**Comment by frank-weinberg** [comment] 2023-05-15 14:12
Thinking about it, there is an argument to make the Jam Score "click me" orange when it has an OS offset without a reason filled in. You'll either want to remove the offset or enter a reason for it. Once a reason has been entered the red dot as an indicator that there's something recorded here should suffice.

**Comment by admdikramr** [comment] 2023-05-15 21:26
"Move Trip" would solve this problem effectively and concisely.

> ad 3: How do you even do this? The common way to get a non-jam is to start a jam when there should have been a timeout and then quickly pressing timeout instead of using undo+replace. But that doesn't put points in the non-jam.

At the end of the jam, I hit "stop jam" then thought "oops that was wrong" so I hit "start jam" but then I realized I wasn't wrong so I hit "stop jam again." So within half a second (not a big deal) we increased the jam number by 1 and nobody noticed until a few more jams had passed, then I didn't have the chance to even try to fix it until the timeout because "delete jam" didn't do anything (per other thread). The reason I made this error is that I had key confusion because I arrived at the game having practiced using spacebar to start the jam, however, the HNSO noted that there is another SBO in the area who makes the same error frequently.

> the easily miss-able red dot was instead the trip colored red

I think this would have led me to understand what was going on faster, but I still would need a way to fix it -- a way to say "this is correct, it's not an offset."

> opening a "Do you really want to edit the points?" popup for an inline edit is an absolute no go as that would block hotkeys

Good point.

> the instances where a change of an old scoring trip should not cause an OS offset are so rare that the ability to manually remove the OS offset afterwards should be sufficient.

Do you have data on how rare this is? My guess is that most use cases of CRG do not "need" or care much about the SK paperwork. I certainly didn't audit it but when I would glance back and forth between the actual SK's paperwork and CRG's, there were frequently differences. I'd bet that if someone were to be meticulous about CRG's paperwork matching the "real" SK paperwork you would frequently find a need to correct historic jam numbers. (Although, the most likely case is probably just adding/removing 0's from the end.)

However, if by "manually remove the OS offset afterwards" you mean, providing the user a way to say "this is a paperwork correction, not an offset," I think I tentatively agree.

> You'll either want to remove the offset or enter a reason for it.

I'm not sure what the language of "remove the offset" here means. It could mean "remove the change that you made; revert to the original points recorded" or it could mean "accept the new score as correct, rather than treat it as an offset." I need the latter. If that functionality exists already, I completely missed it.

However, please let me call step 6 back into your attention: I can delete a jam with an "apparent" score of 0 even if there are "real" points in that jam. Deleting this changes the displayed score. Surely this is a bug?

**Comment by frank-weinberg** [comment] 2023-05-15 22:20
I realize this is not the point of the ticket but for completeness:

Quickly pressing another button when you pressed a wrong (clock) button is always the wrong move. I know it's hard to get over that instinct (I took quite some time myself) but with "Replace on Undo" you have the time to make a conscious assessment of what you did, what you should have done, and then replace the action accordingly with the software rewriting history to fit your new choice. However, once you did press another clock button, the previous action is set in stone.

> I'd bet that if someone were to be meticulous about CRG's paperwork matching the "real" SK paperwork you would frequently find a need to correct historic jam numbers. 

In my neck of the Derby woods discrepancies between SK paperwork and CRG are not too common and more often the reason is an inexperienced SK missing something than CRG having it wrong. Specifically, this is the first I have ever heard of someone actually having to make a correction where overriding an OS offset was the appropriate way of handling it.

> I'm not sure what the language of "remove the offset" here means.

If you click on the Jam score (where the tiny red indicator appeared and the "click me" color will be in the future) you get a popup where you can edit amount and reason of the OS offset for the Jam. This includes the possibility to set the amount to 0.

> Deleting this changes the displayed score. Surely this is a bug?

Yes. I did acknowledge that in may first comment and it will be fixed in the next release.

**Comment by admdikramr** [comment] 2023-05-15 23:29
As a longtime software developer, the idea that the user's basic instinct is "wrong" and that you will have to take some time to get over it, is usually understood to be a failure of the product. Because most CRG users are non-experts and most leagues' rotating door of NSOs mean that the vast majority of users will not have had time to get over the basic instinct, suggest to me that this would be an area for future development. (In my league, skaters who are not cleared to scrimmage do a rotation or two through NSO positions and then get cleared to scrimmage and rarely NSO again.)

In your neck of the woods do you often have newbie SBOs? I feel like the question of whether the product is being developed for a newish user vs. an experienced user may bend certain design decisions away from the more common use cases. Certainly as it is being developed BY excellent well-practiced SBOs there is a risk of optimizing for the "power user" rather than the common user.

Thanks for explaining how to manage the offset. I think my feedback here is that marking a change as an offset should be something that the user has to do, rather than it being automatic, and having it be something the user has to undo. The reason for this is that score offsets are very rare, and that many NSOs may not even be aware of them.

**Comment by frank-weinberg** [comment] 2023-05-16 16:16
> As a longtime software developer, the idea that the user's basic instinct is "wrong" and that you will have to take some time to get over it, is usually understood to be a failure of the product.

If you can tell me how to distinguish a stop-start due to the SBO having pressed stop in error from a stop-start due to the SBO realizing at the end of lineup that they missed pressing stop at the end of the previous jam, I'll happily adjust the software. Until then the above advice is the best I can do.

> In your neck of the woods do you often have newbie SBOs? 

That depends on how you define "often". But they are a regular occurrence. And they tend to fare no worse than they did with non-stats-CRG.

**Comment by admdikramr** [comment] 2023-05-16 17:53
I don't think there is a need in the software to distinguish "start-stop" from "stop-start," because the operator knows what they did. My proposed solution is to allow the operator to fix it more simply and more quickly, i.e., to have a gameplay-centric fix rather than a paperwork-centric fix that requires multiple steps because of the paperwork implementation.

Put differently, the multi-step paperwork-centric fix to the "simple" issue (simple in terms of cause, and in terms of impact on the game) is a problem in and of itself, because it is dangerous to attempt to fix during gameplay, and the severity of the issue does not justify a timeout. The result was "I guess this will just be wrong for several jams until a timeout is called," which I think should be understood to be bad.

In this scenario we also observed the multi-step paperwork-centric fix to open us up to additional bugs and errors due to the choice of steps to fix it in the paperwork. Different SBOs will take different approaches to fix different gameplay problems if they need to translate it in real time; this increases the blast radius for any error.

**Comment by WishboneBreaker** [comment] 2023-05-16 18:35
If I read this right, in the scenario Muffin described, as visible to the audience the score was correct, it was the jam number that was displaying incorrectly per the game events.

To fix the jam number, Muffin had to delete the jam he added in error. But to delete the jam he added in error, he had to delete the scores -- scores that were already displayed correctly at the time the points were earned. And this cascaded into a snowball of offsets.

But (if I understand correctly) what Muffin really needed in that exact moment was a way to decrease the jam number. Adding a jam number just so the visible scoreboard is correct is pretty easy, and I think intuitive (if you don't care about the paperwork): just add a jam, right? But it's decreasing the visible jam number that is tougher.

Similar to the score adjustment/stash, can there be a "negative jam" stash option? Something that would decrease the displayed jam number?

**Comment by frank-weinberg** [comment] 2023-05-16 18:55
> can there be a "negative jam" stash option?

If I had a good way of doing a jam number offset, I would have already implemented it to deal with JRDA INJ jams.

> My proposed solution is to 

reimplement non-stats-CRG on top of stats-CRG. Been there, heard that. Still not interested. Even less so now that we have committed to a freeze of the operator workflow until the end of the season. As YOU asked for.

**Comment by admdikramr** [comment] 2023-05-16 19:53
> As YOU asked for 

My apologies -- I did not mean to convey a sense of urgency for "direct control over the visual field." It is not even a very big problem that the jam number is wrong on the scoreboard. I'm not asking for this to be fixed fast or to be released before the usual cycle.

I also (personally) don't have an opinion about whether you use the statsbook as the underlying data model for CRG. Perhaps that comment was directed at Wishbone but personally I do not hold the opinion that the statsbook is a "bad" data model or that we shouldn't goal on basing the overall flow of information on it. I haven't read the code either.

I'm satisfied for this specific issue if we agree that an easy jam number offset is desirable, and targeting release in 2024, but also nothing that we do not have an implementation plan. Similarly if we are aligned that a human operator should have fast control over anything on the official display **as a philosophy** I am not pushing anybody to fix this immediately or prior to the normal release cycle.

I apologize if this was not clear from the beginning. My usual process of filing a ticket does not inherently carry any sense of urgency! The only urgent thing here is the bug from step 6 which is already being handled.

**Comment by frank-weinberg** [comment] 2023-05-16 20:51
I'm not committing to implementing a single button Jam number change at any point as I see no way of doing that that isn't way too much effort for the gain.

It takes two mistakes in succession to create a jam that should not be there in the first place - pressing a wrong clock control and then pressing another clock control instead of undo. Accordingly it doesn't happen that frequently, making it acceptable that fixing it takes two clicks.

And yes, you can make the situation worse and harder to fix by then adding points to the jam that shouldn't be there, meaning that you will have a wrong jam number until the next timeout. But given that based on available data (1 report in 4 years) this is a really rare scenario and the jam number is non-essential, I consider this acceptable as well.

**Comment by WishboneBreaker** [comment] 2023-05-17 11:17
I mean, we probably had the wrong jam number stuck on the display in at least 3 games just at the OPE!n, because it's not intuitive how to immediately fix it. And that was just one event where over half of all the officials (refs and NSOs) had NSOd at a WFTDA post season event and we still couldn't fix these things timely before halftime. The event was streaming, so it's not like it ruined the world or sanctioning because the jam numbers were off. But they were off, live, for the world to see.

I think having 100% wrong info on the display without intuitive ways to change it is something to consider to put on the to do list to change when time and bandwidth allows.

**Comment by frank-weinberg** [comment] 2023-05-17 16:06
I've had an idea how it could be possible to turn panicked key pressing into "the right thing":

When the operator presses two different clock controls within a second, the second one is turned into an Undo with replace. Possible scenarios:
- When the second key was meant to replace the first, pressing it once more (which is presumably what a panicked operator will do) will do just this replacement.
- When the second key was meant to undo the first, pressing it again will have the screen remain in replace mode. The most likely thing they'll try next is Undo, which will give them the desired result.
- Even Muffin's Stop-Start-Stop would have lead to the correct result.
- And in any case the final result is a single action that can be accessed by an Undo once the operator has started thinking again.

This should catch a majority of jams that shouldn't be there, reducing the impact of the jam number being difficult to correct.

(Side note: Pressing the same clock control twice within a second already leads to the second press being ignored.)

**Comment by WishboneBreaker** [comment] 2023-05-17 16:29
That fix would fix one reason this kind of thing happens. It sounds like a good idea.

But there's other reasons extra jams get added erroneously. It's a shame that instead of allowing the user to quickly change something after the fact if they want to, instead we have to prevent paperwork errors in this way. It's like if our car's navigation software wouldn't let us turn left unless its maps said there was a road there. "I'm smarter than you, car! If I want to turn left it's upsetting when you won't let me!" Like Muffin said, in an ideal world the software would allow the user to make changes intuitively in the moment once errors are noticed -- errors that perhaps occurred 4 jams ago.

**Comment by frank-weinberg** [comment] 2023-05-17 16:50
Once again: It's not that I'm opposed to having a jam offset, it's that with the internal data structures we have, doing it is very difficult.

**Comment by WishboneBreaker** [comment] 2023-05-17 17:08
Yes, and your solution sounds like a good idea to address one potential error until a way can be devised to change the overall user experience. Hopefully it's acceptable to state preferences/ideal states/pie-in-the-sky-dreams even when they're not currently feasible given time/motivation/abilities/other limitations/perceived demand/etc.

**Closed as completed** 2023-05-19 14:32 UTC
