### ISSUE TITLE
[BUG] Undo-Button does not react during first jam

### ISSUE THREAD

**Issue by charlie-chaperon** [rollerderby/scoreboard#685] opened 2024-03-21 15:13 UTC
**Short summary**
This happened during last weekend at BCRDs Multigame weekend. First day and game of the event: Namur Roller Derby vs. Rayo  Dockers (March 16th 2024).

The event was streamed online, but this particular game still needs to be uploaded. You can probably watch the issue happen later.
I was SBO of the game. When the rolling whistle sounded, I accidentally hit Start Jam instead of Start Lineup. When I wanted to correct this by hitting Undo, it did not react. Neither pressing the shortkey nor clicking Undo worked. The short fix was to stop the jam, start a timeout, reset the Period clock and delete the first jam and timeout. After that, the Scoreboard worked as expected without any further issues.

**Steps to reproduce / How it happened during the event**
1.Start a new game from an uploaded Statsbook. You can use the finished Statsbook, but I can provide the blank Statsbook that was used, if needed.
2. When the Time to Derby counter reaches 30, start the game by hitting Start jam (shortkey = q)
3. Hit Undo (shortkey = r)

The undo button would not react. The jam needs to be end first.
Please note: I haven't been able to reproduce the issue with these instructions! Doing this on my own laptop (lenovo ideapad with Debian12 linux) with a copy of the CRG from the weekend just worked fine.

**Expected behavior**
Hitting the Undo button should reset the game. Instead of starting the first jam, it would reset the period clock to 30:00.

**Scoreboard files**
you can download the autosave files here: https://boxup.uni-potsdam.de/s/okNfHpRpFksbnwo
password (mandatory): Eastsidestory2024

**CRG setup**
- Version 2023.5
- user for shortkey setup: charlie

**hardware**
 - MacBookPro14,2 - MacOS Ventura Version 13.6.5 (22G621)
 - Google Chrome Version 122.0.6261.129 (Offizieller Build) (x86_64)
 - we installed several custom keyboards. The Macbook recognised all of them. Since the error only happened once, it's rather unlikely that keys weren't recognised. I didn't need to change shortkeys after my short fix.

**Additional context**
Footage on Youtube: https://www.youtube.com/watch?v=CjtTreKh31M&list=PLJ7qnWIdQOiLvh72wOO3Jsf0xjuNJiCYX&index=1

**Comment by charlie-chaperon** [comment] 2024-03-23 13:29
I updated the description and shared the link to youtube footage. You can observe the issue well.

**Comment by JeneralPain** [comment] 2024-03-23 20:06
Thanks Charlie,bullseye and myself will take a look and see if we can figure it out.Sent from my iPhoneOn 24 Mar 2024, at 00:30, charlie-chaperon ***@***.***> wrote:﻿
I updated the description and shared the link to youtube footage. You can observe the issue well.

**Comment by JeneralPain** [comment] 2024-03-30 10:30
@charlie-chaperon : Couple of questions:
- The statsbook used, was it edited in Google Drive/Google Docs? 
- The bookworm server, what version of Java?

**Comment by frank-weinberg** [comment] 2024-03-30 11:04
The one file that might provide some insight into what happened under the hood is `logs/crg.log`. Unfortunately that is not included in the files provided. @charlie-chaperon can you add it?

**Comment by charlie-chaperon** [comment] 2024-03-30 13:22
@frank-weinberg I added the crg.log to the cloud drive

@JeneralPain 

- Java of my Debian machine:

```
java --version
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Debian-1deb12u1, mixed mode, sharing)
```
Do you also need the java version of the host machine (MacBook)?

- I will ask about the Statsbook. I did not prepare / edit it.

**Comment by frank-weinberg** [comment] 2024-03-30 13:38
That log pointed at a separate missing feature (uploading a blank statsbook should overwrite an existing file). But nothing related to this incident.
So this happened once, left no trace in the log and is not reproducible, even using the same statsbook. At this point there is little value in guessing wildly at what the cause may have been, so I'm closing this ticket. If this behaviour comes up again, let me know about it.

**Closed as not planned by frank-weinberg** 2024-03-30 13:38 UTC
Labels: bug
