### ISSUE TITLE
[BUG - 2023.7 and 2025-Beta4] Period advances to P2 before starting the game

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#781] opened 2024-10-27 06:31 UTC
**Describe the bug**
The Period Count advances by 1 each time the Intermission Clock countdown finishes regardless of if the following period hasn't actually started

**To Reproduce**
1. Have the Intermission Clock running and finish the countdown to 0:00 [Period will now advance to P1 "Time to Derby" or P2 if "Intermission"]
2. Set a new Intermission Time
3. Start the Intermission Clock again
4. Wait for the Intermission Clock to finish countdown to 0:00
5. Period number will now advance by one, even though the Period the intermission was leading into had not actually started

This has been identified and raised in the Facebook group a few times, but was unable to be replicated - until someone saw the exact circumstances and logged the full steps and posted it this weekend. 
I've validated that this occurs in both 202.7 and 2025-Beta4, as well as occurring both prior to the game starting, and during the Intermission - **HOWEVER** it will not progress past the number of Periods configured in the ruleset. So if there are 2 Periods set in the ruleset, having multiple intermissions countdowns between P1 and P2 will not cause any issues (And there will only every be 1 additional period prior to P1 starting) - but if there are 4 periods, there could be multiple blank periods added

**Expected behavior**
Period counter should increment when the Period Clock starts for the first time, rather than when the Intermission Clock stops. "P1 Upcoming" and "P2 Upcoming" etc messages would then use _current period plus 1_ as the "Upcoming" period number

**Screenshots**
https://github.com/user-attachments/assets/7e1b7eaa-b748-4d1f-bc0d-9fda5d85f920
(Taken from FB post)

**Version:**
2023.7 and 2025-Beta.4

**If this issue occurred on a computer, please complete the following information:**
- OS and version: WIndows 11 Pro 24H2 build 26100.2161 and WSL 2 running Ubuntu
- Browser: Chrome
- Version 130.0.6723.70

**Additional context**

**Comment by frank-weinberg** [comment] 2024-10-27 08:24
Really nice find on those steps to reproduce. I knew of the general bug but this is the missing piece that I needed to pin it down. Now I fully understand what in the code is responsible. (Fixing it without breaking something else could still be a bit tricky, but I am optimistic that I'll be able to do that.)

**Comment by queekusme** [comment] 2024-10-27 08:25
I believe the issue may lie in GameImpl.java, specifically L851

Iirc the following line may have been the cause

`ic.getTimeRemaining() < ic.getTimeElapsed()`

However I'm not sure how this should be fixed, there is a comment on subsequent lines which indicates that a change was previously made to fix an issue

**Comment by queekusme** [comment] 2024-10-27 08:28
@frank-weinberg if you want any testing done before/during PR lmk and I can get myself and the person who helped to try recreate now we know what caused it

**Comment by frank-weinberg** [comment] 2024-10-28 19:30
Testing should be fine - I have now written a unit test covering the scenario.

As to where it is: I don't think the problem is a single line - When the period clock has run down we advance to the next period - and that's needed at this time in order for the "Coming Up" indication to show the right period number.
But if the intermission clock is then restarted before the period actually starts this is treated as the next intermission instead of a return to the prior one, which immediately causes the wrong type of intermission to be shown ("Intermission" instead of "Time To Derby"). Once the intermission clock has run down again, we advance to the next period again (if there is a next period) and have the "ghost period" in the data.

So the proper solution should be to add a hook to the intermission clock being started and if at that point the current period has not started, undo the period advancement. Then everything should behave as desired.

**Closed as completed** 2024-10-29 06:39 UTC
Labels: bug
